### ISSUE TITLE
Crashes with an empty array

### ISSUE THREAD

**Issue by synixebrett** [LordGolias/sqf#41] opened 2018-07-27 10:51 UTC
sqflint is crashing with the line
```sqf
["acre2$defaultpttkey", []] call EFUNC(common,setkey);
```
If I change it to not have that empty array, it works just fine.

Using version 0.3.1

**Comment by DAmNRelentless** [comment] 2018-07-27 17:06
Why would you send an empty array as a parameter to a function?

**Comment by synixebrett** [comment] 2018-07-27 23:24
There are many different use cases for empty arrays.

In the code above it is unbinding a CBA keybind.
Setting a units loadout will most likely have empty arrays in the loadout.

Even just `private _array = [];` will cause sqflint to crash.
I can't run sqflint on a third of the files I am working on due to this bug with empty arrays.

**Comment by LordGolias** [comment] 2018-07-29 20:21
Duplicate of #38. This is fixed in master branch.

**Closed by LordGolias** 2018-07-29 20:21 UTC

**Comment by LordGolias** [comment] 2018-07-29 21:03
I've published a new version of it, 0.3.2, that contains this bug fix. You should be able to pip install it. Hope it helps.
